env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'

extends:
  - '@thedeveloper/eslint-config-ts-styleguide'

rules: {}
